var hierarchy =
[
    [ "actor_entity_s", "structactor__entity__s.html", null ],
    [ "animation_frame_s", "structanimation__frame__s.html", null ],
    [ "bone_frame_s", "structbone__frame__s.html", null ],
    [ "bone_tag_s", "structbone__tag__s.html", null ],
    [ "BoundingBox", "class_bounding_box.html", null ],
    [ "BoundingSphere", "class_bounding_sphere.html", null ],
    [ "BoundingVolume", "class_bounding_volume.html", null ],
    [ "box_s", "structbox__s.html", null ],
    [ "Camera", "class_camera.html", null ],
    [ "client_s", "structclient__s.html", null ],
    [ "CollisionObject", "class_collision_object.html", null ],
    [ "color_s", "structcolor__s.html", null ],
    [ "Emitter", "class_emitter.html", null ],
    [ "Entity", "class_entity.html", null ],
    [ "entity_s", "structentity__s.html", null ],
    [ "gl_font_t", "structgl__font__t.html", null ],
    [ "gl_string_s", "structgl__string__s.html", null ],
    [ "GLString", "class_g_l_string.html", null ],
    [ "Light", "class_light.html", null ],
    [ "List< T >", "class_list.html", null ],
    [ "ListNode< T >", "class_list_node.html", null ],
    [ "Map< K, D >", "class_map.html", null ],
    [ "Map< unsigned int, int >", "class_map.html", null ],
    [ "MapNode< K, D >", "class_map_node.html", null ],
    [ "MapNode< unsigned int, int >", "class_map_node.html", null ],
    [ "Mass", "class_mass.html", null ],
    [ "Matrix", "class_matrix.html", null ],
    [ "Md3", "class_md3.html", null ],
    [ "md3_animation_s", "structmd3__animation__s.html", null ],
    [ "md3_boneframe_s", "structmd3__boneframe__s.html", null ],
    [ "md3_mesh_s", "structmd3__mesh__s.html", null ],
    [ "md3_skin_s", "structmd3__skin__s.html", null ],
    [ "md3_tag_s", "structmd3__tag__s.html", null ],
    [ "md3_texel_s", "structmd3__texel__s.html", null ],
    [ "md3_texture_s", "structmd3__texture__s.html", null ],
    [ "md3_tri_index_s", "structmd3__tri__index__s.html", null ],
    [ "md3_vertex_s", "structmd3__vertex__s.html", null ],
    [ "Md3AnimModel", "class_md3_anim_model.html", null ],
    [ "model_mesh_s", "structmodel__mesh__s.html", null ],
    [ "mtk_image_tga_s", "structmtk__image__tga__s.html", null ],
    [ "MtkImage", "class_mtk_image.html", null ],
    [ "Network", "class_network.html", null ],
    [ "network_frame_s", "structnetwork__frame__s.html", null ],
    [ "network_packet_s", "structnetwork__packet__s.html", null ],
    [ "OpenGLMesh", "class_open_g_l_mesh.html", null ],
    [ "Particle", "class_particle.html", null ],
    [ "ParticleMass", "class_particle_mass.html", null ],
    [ "portal_s", "structportal__s.html", null ],
    [ "psa_anim_info_t", "structpsa__anim__info__t.html", null ],
    [ "psa_key_frame_t", "structpsa__key__frame__t.html", null ],
    [ "PSAAnimation", "class_p_s_a_animation.html", null ],
    [ "psk_bone_t", "structpsk__bone__t.html", null ],
    [ "psk_face_t", "structpsk__face__t.html", null ],
    [ "psk_material_t", "structpsk__material__t.html", null ],
    [ "psk_vtxw_t", "structpsk__vtxw__t.html", null ],
    [ "psk_weight_t", "structpsk__weight__t.html", null ],
    [ "PSKModel", "class_p_s_k_model.html", null ],
    [ "PSKModelRenderer", "class_p_s_k_model_renderer.html", null ],
    [ "Quaternion", "class_quaternion.html", null ],
    [ "quaternion_s", "structquaternion__s.html", null ],
    [ "rbtree_s", "structrbtree__s.html", null ],
    [ "rect_s", "structrect__s.html", null ],
    [ "Render", "class_render.html", null ],
    [ "RenderRoom", "class_render_room.html", null ],
    [ "room_mesh_s", "structroom__mesh__s.html", null ],
    [ "sector_s", "structsector__s.html", null ],
    [ "Simulation", "class_simulation.html", [
      [ "GravitySimulation", "class_gravity_simulation.html", null ],
      [ "SpringSimulation", "class_spring_simulation.html", null ]
    ] ],
    [ "skeletal_model_s", "structskeletal__model__s.html", null ],
    [ "SkeletalModel", "class_skeletal_model.html", null ],
    [ "Sound", "class_sound.html", null ],
    [ "sprite_s", "structsprite__s.html", null ],
    [ "sprite_seq_s", "structsprite__seq__s.html", null ],
    [ "Stack< T >", "class_stack.html", null ],
    [ "StackNode< T >", "class_stack_node.html", null ],
    [ "static_model_s", "structstatic__model__s.html", null ],
    [ "System", "class_system.html", [
      [ "GLUTSystem", "class_g_l_u_t_system.html", null ],
      [ "SDLSystem", "class_s_d_l_system.html", [
        [ "OpenRaider", "class_open_raider.html", null ]
      ] ]
    ] ],
    [ "texel_s", "structtexel__s.html", null ],
    [ "Texture", "class_texture.html", null ],
    [ "texture_tri_s", "structtexture__tri__s.html", null ],
    [ "TombRaider", "class_tomb_raider.html", null ],
    [ "TombRaider1", "class_tomb_raider1.html", null ],
    [ "tr2_anim_command_s", "structtr2__anim__command__s.html", null ],
    [ "tr2_anim_dispatch_s", "structtr2__anim__dispatch__s.html", null ],
    [ "tr2_animated_texture_s", "structtr2__animated__texture__s.html", null ],
    [ "tr2_animation_s", "structtr2__animation__s.html", null ],
    [ "tr2_boxes_s", "structtr2__boxes__s.html", null ],
    [ "tr2_camera_s", "structtr2__camera__s.html", null ],
    [ "tr2_cinematic_frame_s", "structtr2__cinematic__frame__s.html", null ],
    [ "tr2_colour_s", "structtr2__colour__s.html", null ],
    [ "tr2_frame_s", "structtr2__frame__s.html", null ],
    [ "tr2_item_s", "structtr2__item__s.html", null ],
    [ "tr2_mesh_s", "structtr2__mesh__s.html", null ],
    [ "tr2_meshtree_s", "structtr2__meshtree__s.html", null ],
    [ "tr2_moveable_s", "structtr2__moveable__s.html", null ],
    [ "tr2_object_texture_s", "structtr2__object__texture__s.html", null ],
    [ "tr2_object_texture_vert_s", "structtr2__object__texture__vert__s.html", null ],
    [ "tr2_quad_s", "structtr2__quad__s.html", null ],
    [ "tr2_room_data_s", "structtr2__room__data__s.html", null ],
    [ "tr2_room_info_s", "structtr2__room__info__s.html", null ],
    [ "tr2_room_light_s", "structtr2__room__light__s.html", null ],
    [ "tr2_room_portal_s", "structtr2__room__portal__s.html", null ],
    [ "tr2_room_s", "structtr2__room__s.html", null ],
    [ "tr2_room_sector_s", "structtr2__room__sector__s.html", null ],
    [ "tr2_room_sprite_s", "structtr2__room__sprite__s.html", null ],
    [ "tr2_room_staticmesh_s", "structtr2__room__staticmesh__s.html", null ],
    [ "tr2_sound_details_s", "structtr2__sound__details__s.html", null ],
    [ "tr2_sound_source_s", "structtr2__sound__source__s.html", null ],
    [ "tr2_sprite_sequence_s", "structtr2__sprite__sequence__s.html", null ],
    [ "tr2_sprite_texture_s", "structtr2__sprite__texture__s.html", null ],
    [ "tr2_state_change_s", "structtr2__state__change__s.html", null ],
    [ "tr2_staticmesh_s", "structtr2__staticmesh__s.html", null ],
    [ "tr2_textile16_s", "structtr2__textile16__s.html", null ],
    [ "tr2_textile32_s", "structtr2__textile32__s.html", null ],
    [ "tr2_textile8_s", "structtr2__textile8__s.html", null ],
    [ "tr2_tri_s", "structtr2__tri__s.html", null ],
    [ "tr2_vertex_room_s", "structtr2__vertex__room__s.html", null ],
    [ "tr2_vertex_s", "structtr2__vertex__s.html", null ],
    [ "tr4_ai_object_s", "structtr4__ai__object__s.html", null ],
    [ "tr4_animation_s", "structtr4__animation__s.html", null ],
    [ "tr4_extra_camera_s", "structtr4__extra__camera__s.html", null ],
    [ "tr4_object_texture_s", "structtr4__object__texture__s.html", null ],
    [ "tr4_quad_s", "structtr4__quad__s.html", null ],
    [ "tr4_room_light_s", "structtr4__room__light__s.html", null ],
    [ "tr4_tri_s", "structtr4__tri__s.html", null ],
    [ "tr5_animation_s", "structtr5__animation__s.html", null ],
    [ "tr5_cinematic_frame_s", "structtr5__cinematic__frame__s.html", null ],
    [ "tr5_face3_s", "structtr5__face3__s.html", null ],
    [ "tr5_face4_s", "structtr5__face4__s.html", null ],
    [ "tr5_flyby_camera_s", "structtr5__flyby__camera__s.html", null ],
    [ "tr5_light_s", "structtr5__light__s.html", null ],
    [ "tr5_mesh_s", "structtr5__mesh__s.html", null ],
    [ "tr5_moveable_s", "structtr5__moveable__s.html", null ],
    [ "tr5_object_texture_s", "structtr5__object__texture__s.html", null ],
    [ "tr5_object_texture_vertex_s", "structtr5__object__texture__vertex__s.html", null ],
    [ "tr5_room_geometry_s", "structtr5__room__geometry__s.html", null ],
    [ "tr5_room_layer_s", "structtr5__room__layer__s.html", null ],
    [ "tr5_room_s", "structtr5__room__s.html", null ],
    [ "tr5_vertex_s", "structtr5__vertex__s.html", null ],
    [ "Tree< Key, Data >", "class_tree.html", null ],
    [ "Tree< K, MapNode< K, D > * >", "class_tree.html", null ],
    [ "Tree< unsigned int, MapNode< unsigned int, int > * >", "class_tree.html", null ],
    [ "TreeNode< Key, Data >", "class_tree_node.html", null ],
    [ "TreeNode< K, MapNode< K, D > * >", "class_tree_node.html", null ],
    [ "TreeNode< unsigned int, MapNode< unsigned int, int > * >", "class_tree_node.html", null ],
    [ "tris_s", "structtris__s.html", null ],
    [ "ttf_glyph_t", "structttf__glyph__t.html", null ],
    [ "ttf_texture_t", "structttf__texture__t.html", null ],
    [ "UTPackage", "class_u_t_package.html", null ],
    [ "UTPackageProperty", "class_u_t_package_property.html", null ],
    [ "utx_export_table_t", "structutx__export__table__t.html", null ],
    [ "utx_generation_t", "structutx__generation__t.html", null ],
    [ "utx_header_t", "structutx__header__t.html", null ],
    [ "utx_import_table_t", "structutx__import__table__t.html", null ],
    [ "utx_name_table_t", "structutx__name__table__t.html", null ],
    [ "uv_s", "structuv__s.html", null ],
    [ "Vector< Object >", "class_vector.html", null ],
    [ "Vector3d", "class_vector3d.html", null ],
    [ "Vector< animation_frame_s * >", "class_vector.html", null ],
    [ "Vector< bone_frame_s * >", "class_vector.html", null ],
    [ "Vector< bone_tag_s * >", "class_vector.html", null ],
    [ "Vector< box_s * >", "class_vector.html", null ],
    [ "Vector< char * >", "class_vector.html", null ],
    [ "Vector< CollisionObject * >", "class_vector.html", null ],
    [ "Vector< const char * >", "class_vector.html", null ],
    [ "Vector< entity_s * >", "class_vector.html", null ],
    [ "Vector< int >", "class_vector.html", null ],
    [ "Vector< Light * >", "class_vector.html", null ],
    [ "Vector< Mass * >", "class_vector.html", null ],
    [ "Vector< model_mesh_s * >", "class_vector.html", null ],
    [ "Vector< portal_s * >", "class_vector.html", null ],
    [ "Vector< RenderRoom * >", "class_vector.html", null ],
    [ "Vector< room_mesh_s * >", "class_vector.html", null ],
    [ "Vector< sector_s * >", "class_vector.html", null ],
    [ "Vector< skeletal_model_s * >", "class_vector.html", null ],
    [ "Vector< SkeletalModel * >", "class_vector.html", null ],
    [ "Vector< sprite_s * >", "class_vector.html", null ],
    [ "Vector< sprite_seq_s * >", "class_vector.html", null ],
    [ "Vector< static_model_s * >", "class_vector.html", null ],
    [ "Vector< texture_tri_s * >", "class_vector.html", null ],
    [ "vertex_s", "structvertex__s.html", null ],
    [ "ViewVolume", "class_view_volume.html", null ],
    [ "World", "class_world.html", null ],
    [ "world_entity_s", "structworld__entity__s.html", null ]
];