# This is the Open Raider RC file
#####################################

[Video.OpenGL]
Driver=/usr/lib/libGL.so.1
Width=1280
Height=720
FastCard=true
FullScreen=false
Font=~/.OpenRaider/data/test.ttf

[Audio.OpenAL]
Enable=true

[Network.Server]
Enable=false
#Name=OpenRaider Server Beta 1
#Dedicated=true
Port=27910

[Input.Mouse]
SensitivityX=1.0
SensitivityY=1.0

[OpenRaider.Engine]
PakDir=~/.OpenRaider/paks/
AudioDir=~/.OpenRaider/music/
HomeDir=~/.OpenRaider/data/
DisplayFPS=false
MapDebug=false
ModelDebug=false
DumpTexture=false
#Script=tr3/tombPC.dat
#Music=tr4/039_TR4_Title_Q10.wav
#Music=tr4/103_A3_Out_Night.wav
#Music=tr4/108_A8_Coastal.wav
#Map=custom/Yvel.tr2
#Map=custom/villa2.phd
#Map=custom/fenician1.phd
#Map=custom/1984.tr2
#Map=custom/bigchamber.tr4
#Map=custom/cleopal.tr4
#Map=custom/khysos.tr4
#Map=custom/Nasa.tr2
#Map=custom/mansionfrost.tr2
#Map=tr1/gym.phd
#Map=tr1/level1.phd
#Map=tr1/level2.phd
#Map=tr2/unwater.tr2
#Map=tr3/willsden.tr2
#Map=tr3/undersea.tr2
#Map=tr3/scotland.tr2
#Map=tr3/HOUSE.TR2
#Map=tr3/zoo.tr2
#Map=tr3/slinc.tr2
#Map=tr3/temple.tr2
#Map=tr3/shore.tr2
#Map=tr3/chunnel.tr2
#Map=tr4/angkor1.tr4
#Map=tr4/ang_race.tr4
#Map=tr4/karnak1.tr4
#Map=tr4/lake.tr4
#Map=tr4/settomb1.tr4
#Map=tr4/settomb2.tr4
#Map=tr4/title.tr4
#Map=tr5/demo.trc

[OpenRaider.Console]
bind +console 96
bind +forward 119
bind +backward 115
bind +jump 32
bind +crouch 99
bind +left 97
bind +right 100
#bind +attack 122

#r_light 1				# Enable GL Lighting
#r_fog 1				# Enable depth fog
#r_particle 1				# Enable particle test
#r_portal 1				# Enable portal rendering

# Support for external configs
@include ~/.OpenRaider/custom.cfg
