# OpenRaider configuration file

set basedir   "~/.OpenRaider"
set pakdir    "$(basedir)/paks"
set audiodir  "$(basedir)/music"
set datadir   "$(basedir)/data"
set font      "$(datadir)/test.ttf"

set gldriver  "/usr/lib/libGL.so.1" # Not needed for Mac!
set size      "1280x720"

set audio     true # Enable Audio Output
set volume    0.5

set mouse_x   1.0
set mouse_y   1.0

bind console  96
bind forward  119
bind backward 115
bind jump     32
bind crouch   99
bind left     97
bind right    100
# bind attack   122
